### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by jhol**
This branch gets docker image working again by doing the following things...
- Upgrade gstreamer to v1.0.
- Upgrade the base distribution to Debian Jessie.
- Various other minor fixes.

### CODE REVIEW

**Comment by vky** [comment]
Cool! Thanks for this. I'll test it out later today, and merge if I don't run into any problems.

**Comment by jhol** [comment]
Any luck testing this?

**Comment by vky** [comment]
Apologies, I couldn't get to this earlier this week. Working on it now, and have encountered some problems.

In particular, problems begin occuring during this step of the docker build:

```
RUN (virtualenv --system-site-packages . || virtualenv .) \
     && ./bin/python setup.py develop
```

It seems that things require Python 3, and the setup at the top is for Python 2. I'm switching all the things over to Python 3. Once I've got it all working, I'll make a pull request against your branch with the additional changes. Or merge this and push the changes on top.

**Comment by vky** [comment]
To give an update, I'm having problems with the installation of `scikits.audiolab` for the `audio` plugin and with the `--server-name=broadcast` parameter passed to the `lazyserver.sh` script in `entrypoint.sh`.

It doesn't look like `lazyserver.sh` takes that parameter anymore; it looks like the default configuration in `paste.ini` sets things up so that the running instance is not available outside of the container. The `server:broadcast` config option looks like what I want, but don't know how to get it.

`scikits.audiolab` doesn't seem to be getting installed correctly for the `audio` plugin option to be present. Removing the `audio` option gets me to the above `broadcast` issue. I'll be looking into both of these throughout the coming week.

**Comment by vky** [comment]
Present state of investigation can be found on this branch: https://github.com/vky/docker-mediagoblin/tree/fix-things.

**Comment by vky** [comment]
Updating everything to Python 3 seems to have caused me a bunch of trouble. Did figure out how to get past the `--server-name=broadcast` issue, only to be hit with the version of SQLAlchemy ( < v0.9.0 ) is no good for Python 3.4. There's an ticket for it already: https://issues.mediagoblin.org/ticket/5330. In short, users are unable to be created with Python 3.4 and SQLAlchemy v0.8.7.

I tested with modified source that uses SQLAlchemy v1.0.6 and was able to create users and have a semi-functional instance of MediaGoblin working. Uploading a video is resulting in a `WORKER TIMEOUT` for video transcoding, failing in the upload. I could upload an image though.

**Comment by jhol** [comment]
I didn't encounter any of those issues you mention - the image seemed to work OK at the end of my pull request branch. Still it doesn't surprise me that there would be issues with Python 3.

The other issue is externalizing the database and storage volumes. Do you know anything about how to do that? I would say that's the main remaining issue with this docker image.

I had a word with the upstream GMG folks about the possibility of getting the `Dockerfile` up-streamed. Sadly there doesn't seem to be much interest there - still I think this Docker recipe will be very helpful to a lot of people.

**Comment by vky** [comment]
Splitting Postgres into a separate container and setting up volumes for storage/logs/stuff is certainly doable, just need the time to set things up and test it all out.

It looks like there's still more stuff to update, the automated build done by https://hub.docker.com/ failed due to Python 3.4 being used instead of Python 3.3.

**Pull request merged**
